Save args in config when cli_vars is saved
dbt-labs/dbt-rpc pull request #70
Opened 2022-02-02 23:12 UTC by gshank

This is for bug #4583 in dbt-core, var not injected in dbt run snapshot from dbt run invocation in 1.0.0.

2022-02-03 13:51 UTC, leahwicz approved these changes

2022-02-04 09:03 UTC, jtcohen6 commented
Looks good in local testing! I shared a Loom with my experience getting everything set up + verified.

Let me know if you need help with automated/integration testing. The RPC tests work a bit differently (and honestly better) vs. our current `dbt-core` integration testing.

After merging, let's plan to:
- Test using the `development (HEAD)` branch of dbt Cloud (includes all changes from this repo's `main` branch)
- Cut a prerelease, for use alongside `dbt-core==1.0.2rc1`
- If everything looks good, cut a final release, coordinated with `dbt-core==1.0.2` (final)

2022-02-09 12:35 UTC, jtcohen6 commented
@gshank @leahwicz Do we have a clear path forward for this one? Should we proceed with the next steps I listed above?

2022-03-09 15:26 UTC, ChenyuLInx requested changes
We probably should have a test to test this behavior

2022-03-10 14:57 UTC, stu-k commented on tests/test_management.py
> +'''
I'm not sure if this method of testing that the config is as expected is too roundabout, I can modify if it is.

2022-03-10 15:16 UTC, stu-k commented on tests/test_management.py
> +      assert results['results'][0]['node']['compiled_sql'].strip() == 'select 9876 as id'
The compiled sql produces a newline at the beginning of the string, `strip`ping the string removes this.

2022-03-11 15:22 UTC, ChenyuLInx approved these changes
LGTM!

2022-03-11 17:01 UTC, merged